import "@/assets/globals.css";
import NavBar from "@/components/ui/NavBar";
import Image from "next/image";

import 'react-toastify/dist/ReactToastify.css';
import { Footer } from "@/components/layout/Footer/footer";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};
export default function RootLayout({ children }) {

    const isUserAuth = false;

    return (
        <html>
            <body>
                <NavBar auth={isUserAuth} />
                <div style={{ minHeight: '500px' }}>
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
