import "@/assets/globals.css";
import "primereact/resources/themes/lara-light-green/theme.css";
import 'primeicons/primeicons.css';
import 'react-toastify/dist/ReactToastify.css';
import Providers from "@/context/Providers";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html>
            <body>
                {children}
            </body>
        </html>
    );
}
