import "@/assets/globals.css";
import "primereact/resources/themes/lara-light-green/theme.css";
import "primeicons/primeicons.css";
import "react-toastify/dist/ReactToastify.css";
import Providers from "@/context/Providers";
import { AuthProvider } from "@/context/AuthContext";
import NavBar from "@/components/ui/NavBar";
import { PrimeReactProvider } from "primereact/api";
import { Footer } from "@/components/layout/Footer/footer";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // remoção de PrimeReactProvider e AuthProvider para ambiente de desenvolvimento
  return (
    <html>
      <body>
        <NavBar />
        <div style={{ minHeight: "500px" }}>{children}</div>
        <Footer />
      </body>
    </html>
  );
}
