# Generated by Django 5.0.3 on 2024-10-29 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplines',
            name='professors',
            field=models.ManyToManyField(related_name='disciplines', to='users.servant'),
        ),
    ]
