# Generated by Django 5.0.3 on 2024-10-26 18:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplines', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disciplines',
            options={'ordering': ['name'], 'verbose_name': 'Discipline', 'verbose_name_plural': 'Disciplines'},
        ),
        migrations.AddField(
            model_name='disciplines',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, help_text='Select the disciplines that are prerequisites:', related_name='required_disciplines', to='disciplines.disciplines', verbose_name='Prerequisites'),
        ),
        migrations.AddField(
            model_name='disciplines',
            name='syllabus',
            field=models.TextField(blank=True, help_text='Enter the syllabus of the discipline:', max_length=500, verbose_name='Syllabus'),
        ),
        migrations.AlterField(
            model_name='disciplines',
            name='name',
            field=models.CharField(help_text='Enter the name of the discipline:', max_length=100, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Discipline Name'),
        ),
        migrations.AlterField(
            model_name='disciplines',
            name='professors',
            field=models.ManyToManyField(help_text='Select the professors for this discipline:', related_name='disciplines', to='users.usuario', verbose_name='Professors'),
        ),
        migrations.AlterField(
            model_name='disciplines',
            name='workload',
            field=models.CharField(help_text='Enter the workload of the discipline:', max_length=10, validators=[django.core.validators.MinLengthValidator(1)], verbose_name='Workload'),
        ),
    ]
