from .base import *
from .aluno import *
from .anexo import *
from .cronograma import *
from .curso import *
from .disciplina import *
from .edital import *
from .ppc import *
from .prova import *
from .retificacao import *
from .semestre import *
from .servidor import *
from .solicitacao import *