# Generated by Django 5.0.3 on 2024-10-29 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254)),
                ('DateIn', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.abstractuser')),
                ('siape', models.CharField(blank=True, max_length=255)),
                ('servant_type', models.CharField(choices=[('TEACHER', 'Professor'), ('ENSINO', 'Ensino'), ('COORDINATOR', 'Coordenador')], default='Professor', max_length=50)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.abstractuser',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('abstractuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.abstractuser')),
                ('matricula', models.CharField(blank=True, max_length=255)),
                ('course', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('users.abstractuser',),
        ),
    ]
