import "@/assets/globals.css";
import "primereact/resources/themes/lara-light-green/theme.css";
import 'primeicons/primeicons.css';
import 'react-toastify/dist/ReactToastify.css';
import NavBar from "@/components/ui/NavBar";
import { Footer } from "@/components/layout/Footer/footer";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function NoAuthLayout({ children }) {
    return (
        <html>
            <body>
                <NavBar data={false}/>
                <div style={{ minHeight: '500px' }}>
                    {children}
                </div>
                <Footer />
            </body>
        </html>
    );
}
