# Generated by Django 5.0.3 on 2024-10-29 23:23

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=50, unique=True)),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('documentation_submission_start', models.DateTimeField()),
                ('documentation_submission_end', models.DateTimeField()),
                ('proposal_analysis_start', models.DateTimeField()),
                ('proposal_analysis_end', models.DateTimeField()),
                ('result_publication_start', models.DateTimeField()),
                ('result_publication_end', models.DateTimeField()),
                ('result_homologation_start', models.DateTimeField()),
                ('result_homologation_end', models.DateTimeField()),
                ('extra_fields', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
