# Generated by Django 5.1.1 on 2024-10-13 13:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servant',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
