# Generated by Django 5.0.3 on 2024-10-29 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplines', '0002_initial'),
        ('forms', '0001_initial'),
        ('notices', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgecertification',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certification_student', to='users.student'),
        ),
        migrations.AddField(
            model_name='recognitionofpriorlearning',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='recognition_requests', to='forms.attachment'),
        ),
        migrations.AddField(
            model_name='recognitionofpriorlearning',
            name='discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_requisitions', to='disciplines.disciplines'),
        ),
        migrations.AddField(
            model_name='recognitionofpriorlearning',
            name='notice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_notices', to='notices.notice'),
        ),
        migrations.AddField(
            model_name='recognitionofpriorlearning',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recognition_student', to='users.student'),
        ),
    ]
